dynaconf_merge: true
default:
  NAME: user_auth_service
  HOST: 0.0.0.0
  PORT: 8012
  FAST_API_PATH: application.app:service_app
  LOG_LEVEL: INFO
  RELOADED: True
  POSTGRES:
    dialect: asyncpg
    host: localhost
    port: 5432
    login: postgres
    password: postgres
    database: user_auth_service
    pgbouncer: False
    echo: False
    pool_min_size: 10
    pool_max_size: 20
    pool_timeout: 90
    mat_view_time: 15
