"""create_roles_and_permissions

Revision ID: 71e4e233d45e
Revises: d4b9f8997b14
Create Date: 2026-09-13 15:49:37.254000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "71e4e233d45e"
down_revision: Union[str, Sequence[str], None] = "d4b9f8997b14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column(
            "name",
            sa.String(),
            nullable=False,
            comment="Человекочитаемое название разрешения",
        ),
        sa.Column(
            "layer",
            sa.String(),
            nullable=False,
            comment="К чему относится разрешение ('frontend'/'backend'/...)",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_permissions_uuid"), "permissions", ["uuid"], unique=False)
    op.create_table(
        "roles",
        sa.Column("name", sa.String(), nullable=False, comment="Название"),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_roles_uuid"), "roles", ["uuid"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("permission_uuid", sa.UUID(), nullable=False),
        sa.Column("role_uuid", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.ForeignKeyConstraint(
            ["permission_uuid"],
            ["permissions.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["role_uuid"],
            ["roles.uuid"],
        ),
        sa.PrimaryKeyConstraint("permission_uuid", "role_uuid", "uuid"),
        sa.UniqueConstraint(
            "permission_uuid", "role_uuid", name="idx_unique_role_permission"
        ),
    )
    op.create_index(
        op.f("ix_role_permissions_uuid"),
        "role_permissions",
        ["uuid"],
        unique=False,
    )
    op.create_table(
        "user_roles",
        sa.Column("user_uuid", sa.UUID(), nullable=False),
        sa.Column("role_uuid", sa.UUID(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.ForeignKeyConstraint(
            ["role_uuid"],
            ["roles.uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("user_uuid", "role_uuid", "uuid"),
        sa.UniqueConstraint("user_uuid", "role_uuid", name="idx_unique_user_role"),
    )
    op.create_index(op.f("ix_user_roles_uuid"), "user_roles", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_roles_uuid"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_role_permissions_uuid"), table_name="role_permissions")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_roles_uuid"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_permissions_uuid"), table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
