"""create_outbox

Revision ID: b5f6fb892956
Revises: a1b2c3d4e5f6
Create Date: 2026-09-17 21:20:49.288603

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b5f6fb892956"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outboxs",
        sa.Column(
            "event_type", sa.String(), nullable=False, comment="Тип события"
        ),
        sa.Column(
            "sent_at", sa.DateTime(), nullable=True, comment="Время отправки"
        ),
        sa.Column(
            "entity_id",
            sa.UUID(),
            nullable=False,
            comment="Уникальный айди сущности",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "WAITING_FOR_SENDING",
                "SENT",
                "CREATED",
                "UNSENT",
                "ARCHIVED",
                name="event_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.Column(
            "uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_outboxs_entity_id"), "outboxs", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_outboxs_event_type"), "outboxs", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_outboxs_uuid"), "outboxs", ["uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outboxs_uuid"), table_name="outboxs")
    op.drop_index(op.f("ix_outboxs_event_type"), table_name="outboxs")
    op.drop_index(op.f("ix_outboxs_entity_id"), table_name="outboxs")
    op.execute('DROP TYPE IF EXISTS event_status_enum CASCADE')
    op.drop_table("outboxs")
    # ### end Alembic commands ###
